---
- apt_key:
    keyserver: keyserver.ubuntu.com
    id: ACCAF35C
    state: present
  become: true

- apt_repository:
    repo: 'deb http://apt.insynchq.com/ubuntu {{ ansible_distribution_release }} non-free contrib'
    state: present
  become: true

- apt:
    name: insync
    state: latest
    update_cache: true
  become: true
