---
- name: add paa firefox-next
  ansible.builtin.apt_repository:
    repo: ppa:mozillateam/firefox-next
    state: present
  become: true


- name: install firefox
  ansible.builtin.package:
    name: firefox
    state: latest
  become: true
