---
# - name: Add repositories flux gui
#   apt_repository: repo: ppa:nathan-renniewaldock/ppa
#   become: true

- name: install flux
  ansible.builtin.apt:
    name: '{{ item }}'
  become: true
  with_items:
    # - fluxgui
    - redshift
    - redshift-gtk
