---
- name: Add paa ppa gencfsm
  ansible.builtin.apt_repository:
    repo: ppa:gencfsm
    state: present
  become: true


- name: Install encfs
  ansible.builtin.apt:
    name:
      - encfs
      - gnome-encfs-manager
  become: true


# - name: Install configuration
#   ansible.builtin.copy:
#     src: 'Molch Encfs Manager.conf'
#     dest: '{{ home }}/.config/Molch Encfs Manager.conf'
#     mode: '0644'


- name: Pause
  ansible.builtin.pause:
    prompt: "Start EncFS GUI  Directory {{ home }}/Dropbox/Documents  ; Mount {{ home }}/{{ cloudstorage }}"
