---
- name: install encfs
  ansible.builtin.apt:
    name: encfs
  become: true


- name: Download MolchEncfsManager
  ansible.builtin.get_url:
    url: https://moritzmolch.com/apps/files/mencfsm/19.06/MolchEncfsManager.x86_64
    dest: /usr/local/bin/MolchEncfsManager
    mode: '0775'
  become: true


- name: install configuration
  ansible.builtin.copy:
    src: 'Molch Encfs Manager.conf'
    dest: '{{ home }}/.config/Molch Encfs Manager.conf'
    mode: '0644'


- name: pause
  ansible.builtin.pause:
    prompt: "Start EncFS GUI  Directory {{ home }}/Dropbox/Notebooks  ; Mount {{ home }}/Notebooks"
