---
- name: Install git
  ansible.builtin.apt:
    name:
      - git
      - fd-find
      - tig
    state: present
  become: true


- name: Create symlink fd
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: '{{ bin_dir }}/fd'
    state: link


- name: Download bashrc from git
  ansible.builtin.git:
    repo: "git@github.com:OpsCharlie/bash.git"
    dest: '{{ git_dir }}/bash'
    accept_hostkey: true
  register: git_out


- name: Deploy bash config
  ansible.builtin.command: 'bash {{ git_dir }}/__deploy.sh'
  changed_when: false
  when: git_out.changed


- name: Copy bash theme
  ansible.builtin.copy:
    src: base16-railscasts.dark.sh
    dest: '{{ home }}/Downloads'
    mode: "0640"
  register: theme


- name: Run bash theme
  ansible.builtin.command: 'bash {{ home }}/Downloads/base16-railscasts.dark.sh'
  when: theme.changed
