---
- name: Install git
  ansible.builtin.apt:
    name:
      - git
      - fd-find
      - tig
    state: present
  become: true


- name: Create symlink fd
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: '{{ bin_dir }}/fd'
    state: link


- name: Download bashrc from git
  ansible.builtin.git:
    repo: "git@github.com:OpsCharlie/bash.git"
    dest: '{{ git_dir }}/bash'
    accept_hostkey: true
  notify: Deploy bash config


- name: Copy bash theme
  ansible.builtin.copy:
    src: base16-railscasts.dark.sh
    dest: '{{ home }}/Downloads'
    mode: "0640"
  notify: Run bash theme


- name: Flush handlers
  ansible.builtin.meta: flush_handlers
