---
- name: Add repositories ulauncher
  ansible.builtin.apt_repository:
    repo: ppa:agornostal/ulauncher
  become: true

- name: install
  ansible.builtin.apt:
    name:
      - ulauncher
    state: latest
  become: true
