---
- name: install guake
  ansible.builtin.apt:
    name: guake
    state: present
  become: true

- name: copy config
  ansible.builtin.copy:
    src: guake.conf
    dest: /tmp/guake.conf
    mode: '0644'

- name: import conf
  ansible.builtin.shell: dconf load /apps/guake/ < /tmp/guake.conf
  changed_when: false
