---
- name: update grub
  ansible.builtin.command: update-grub
  become: true

- name: Restart networkd-resolve after applying config
  ansible.builtin.command: systemctl restart systemd-resolved
  listen: restart systemd-resolve
  become: true


- name: run sysctl
  ansible.builtin.command: sysctl -p
  become: true
