---
# Usage: ansible-playbook -K local.yml

- name: Configure laptop
  hosts: 127.0.0.1
  connection: local

  vars:
    home: "{{ ansible_user_dir }}"
    git: "git"
    cloudstorage: "{{ home }}/Documents/Dropbox"
    packaging_ubuntu_multiverse_repository: false
    packaging_ubuntu_universe_repository: false
    packaging_ubuntu_restriced_repository: false

  pre_tasks:
    - name: Create destination directory
      ansible.builtin.file:
        path: "{{ home }}/{{ item }}"
        state: directory
        mode: "0750"
      loop:
        - ".local/bin"
        - ".icons"
        - ".fonts"

  roles:
    # - extra_repo     # extra repos
    - ipv6           # disable ipv6 and extras
    # - grub2 #?

    # - encfs
    # - ssh
    # - nemo
    # - bash
    # - zsh
    # - fzf
    # - vim
    # - tmux
    # - evolution
    # - obsidian
    # - vivaldi
    # - networkmanager
    # - networktools
    # - apt-updates
    # - keepassxc
    # - fonts
    # - apport
    # - gnome-tweaks
    # - zeal
    # - shutter
    # - vlc
    # - geany
    # - tools
    # - skype
    # - office

    #### extra software
    # - chrome
    # - onedrive #?
    # - dropbox  # not needed anymore
    # - ansible-tools #?
    # - zim #?
    # - java #?
    # - pac #?
    ## - openxenmanager
    # - firefox #?
    ## - timeshift
    ## - rambox
    ## - beekeeperstudio
    ## - mysqlworkbench
    ## - mixed-content-scan
    ## - scripts     # tools and zabbix notification
    ## - beekeeperstudio
    ## - peek        # gif recorder
    ## - virtualbox
    ## - vagrant
    ## - bingwall
    ## - ppa-manager
    ## - httpstat
    # - tlp     # power manager
    # - translate
    # - filezilla
    # - vscode
    # - dbeaver
    # - libreoffice
    # - pycharm
    # - powershell
    # - masterpdf
    # - bleachbit
    # - ulauncher
    # - flameshot
    # - testssl
    # - guake
    # - postman
