---
# Usage: ansible-playbook -K local.yml

- hosts: 127.0.0.1
  connection: local

  vars:
    - home: '{{ ansible_user_dir }}'
    - cloudstorage: '{{ home }}/Documents/Dropbox'
    - packaging_ubuntu_multiverse_repository: true
    - packaging_ubuntu_universe_repository: true
    - packaging_ubuntu_restriced_repository: true


  pre_tasks:
    - name: Create destination directory
      ansible.builtin.file:
        path: "{{ home }}/{{ item }}"
        state: directory
        mode: "0750"
      loop:
        - ".local/bin"
        - ".icons"
        - ".fonts"


  roles:
    # - extra_repo     # extra repos
    # - ipv6           # disable ipv6 and extras
    # - grub2

    # - encfs
    # - ssh
    # - nemo
    # - bash
    # - zsh
    # - fzf
    # - vim
    # - tmux
    # - onedrive
    # - evolution
    # - zim
    - obsidian
    # - java #?
    # - pac #?
    # - chrome
    # - vivaldi
    # - firefox #?
    # - networkmanager
    # - networktools
    # - ansible-tools
    # - apt-updates
    # - keepassxc
    # - fonts
    # - apport

    #### extra software
    # - dropbox  # not needed anymore
    ## - openxenmanager
    ## - timeshift
    ## - shutter
    ## - rambox
    ## - beekeeperstudio
    ## - mysqlworkbench
    ## - mixed-content-scan
    ## - scripts     # tools and zabbix notification
    ## - beekeeperstudio
    ## - peek        # gif recorder
    ## - virtualbox
    ## - vagrant
    ## - bingwall
    ## - ppa-manager
    ## - httpstat
    # - tlp     # power manager
    # - translate
    # - filezilla
    # - vscode
    # - dbeaver
    # - libreoffice
    # - office
    # - pycharm
    # - powershell
    # - masterpdf
    # - bleachbit
    # - ulauncher
    #
    # - gnome-tweaks
    # - zeal
    # - flameshot
    # - testssl
    # - vlc
    # - geany
    # - tools
    # - guake
    # - postman
    # - skype
