---
- name: Install dbeaver key
  ansible.builtin.apt_key:
    url: https://dbeaver.io/debs/dbeaver.gpg.key
    state: present
  become: true


- name: Install dbeaver repo
  ansible.builtin.apt_repository:
    repo: deb https://dbeaver.io/debs/dbeaver-ce /
    state: present
    update_cache: true
  become: true


- name: Install dbeaver
  ansible.builtin.apt:
    name: dbeaver-ce
    state: present
  become: true


# - name: install dbeaver
#   snap:
#     name: dbeaver-ce
#     state: present
#   become: true
