---
- name: Install vscode key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes


- name: Install vscode repo
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/code stable main
    state: present
    update_cache: yes
  become: yes


- name: Install code
  apt:
    name: code
    state: present
  become: yes


# - name: install vscode
#   snap:
#     name: code
#     classic: true
#     state: present
#   become: true


- name: install code extensions
  shell: 'code --install-extension {{ item }}'
  loop: '{{ vs_extensions }}'
  register: vs_out
  changed_when: '"already installed" not in vs_out.stdout'
