---
- name: Install alacritty
  ansible.builtin.package:
    name: alacritty
    state: present


- name: Download opencode from git
  ansible.builtin.git:
    repo: "git@github.com:OpsCharlie/opencode.git"
    dest: '{{ git_dir }}/opencode'


- name: Deploy opencode
  ansible.builtin.command: 'bash {{ git_dir }}/opencode/__deploy.sh'
  register: deploy_opencode
  changed_when: "'latest version' not in deploy_opencode.stdout"
