---
# install freeoffice
- name: add softmaker repo key
  apt_key:
    data: "{{ lookup('file', 'softmaker.repository.gpg') }}"
    state: present
  become: yes

- name: add softmaker repo
  apt_repository:
    repo: 'deb http://shop.softmaker.com/repo/apt stable non-free'
    state: present
    update_cache: yes
  become: yes

- name: install softmaker
  apt:
    name: softmaker-freeoffice-2021
    state: latest
  become: yes

- name: install freeoffice license
  copy:
    dest: /etc/SoftMaker/offree2021.lic
    src: '{{ cloudstorage }}/carl/etc/SoftMaker/offree2018.lic'


# install onlyoffice
- name: install onlyoffice snap
  snap:
    name: onlyoffice-desktopeditors
    state: present
  become: yes
