---
# - name: Add repositories zeal
#   apt_repository:
#     repo: 'ppa:zeal-developers/ppa'
#   become: yes
#   become_method: sudo

- name: install
  ansible.builtin.apt:
    name:
      - zeal
    state: latest
  become: true
