---
- name: keepassxc
  ansible.builtin.apt:
    name: keepassxc
    state: present
  become: true

- name: copy keepass config
  ansible.posix.synchronize:
    src: '{{ cloudstorage }}/carl/.config/keepassxc/'
    dest: '{{ home }}/.config/keepassxc/'
