---
- name: Add repositories libreoffice
  ansible.builtin.apt_repository:
    repo: ppa:libreoffice/ppa
  become: true

- name: install
  ansible.builtin.apt:
    name:
      - libreoffice
    state: latest
  become: true
