---
# - name: add zsh completions apt key
#   apt_key:
#     url: 'https://download.opensuse.org/repositories/shells:zsh-users:zsh-completions/xUbuntu_{{ ansible_distribution_version }}/Release.key'
#   become: true
#
#
# - name: add zsh completions repository
#   apt_repository:
#     repo: 'deb http://download.opensuse.org/repositories/shells:/zsh-users:/zsh-completions/xUbuntu_{{ ansible_distribution_version }}/ /'
#     filename: 'zsh-competions'
#   become: true


- name: install git
  ansible.builtin.apt:
    name:
      - git
      - zsh
#      - zsh-completions
    state: present
  become: true


- name: create {{ home }}/apps directory
  ansible.builtin.file:
    path: '{{ home }}/apps'
    state: directory
    mode: '0755'


- name: download zsh from git
  ansible.builtin.git:
    repo: "https://github.com/OpsCharlie/zsh.git"
    dest: '{{ home }}/apps/zsh'
  register: git


- name: install lxc completeion
  ansible.builtin.copy:
    dest: /usr/share/bash-completion/completions/lxc.zsh
    src: lxc.zsh
    mode: '0644'
  become: true


- name: deploy zsh config
  ansible.builtin.command: 'bash {{ home }}/apps/zsh/__deploy.sh'
  when: git.changed
