---
- name: Install git
  ansible.builtin.apt:
    name:
      - git
      - zsh
    state: present
  become: true


- name: Download zsh from git
  ansible.builtin.git:
    repo: "git@github.com:OpsCharlie/zsh.git"
    dest: '{{ git_dir }}/zsh'
    accept_hostkey: true
  register: git_out


- name: Install lxc completion
  ansible.builtin.copy:
    dest: /usr/share/bash-completion/completions/lxc.zsh
    src: lxc.zsh
    mode: '0644'
  become: true


- name: Deploy zsh config
  ansible.builtin.command: 'bash {{ git_dir }}/zsh/__deploy.sh'
  when: git_out.changed
