---
# - name: add zsh completions apt key
#   apt_key:
#     url: 'https://download.opensuse.org/repositories/shells:zsh-users:zsh-completions/xUbuntu_{{ ansible_distribution_version }}/Release.key'
#   become: true
#
#
# - name: add zsh completions repository
#   apt_repository:
#     repo: 'deb http://download.opensuse.org/repositories/shells:/zsh-users:/zsh-completions/xUbuntu_{{ ansible_distribution_version }}/ /'
#     filename: 'zsh-competions'
#   become: true


- name: Install git
  ansible.builtin.apt:
    name:
      - git
      - zsh
#      - zsh-completions
    state: present
  become: true


- name: Create {{ home }}/{{ git }} directory
  ansible.builtin.file:
    path: '{{ home }}/{{ git }}'
    state: directory
    mode: '0755'


- name: download zsh from git
  ansible.builtin.git:
    repo: "git@github.com:OpsCharlie/zsh.git"
    dest: '{{ home }}/{{ git }}/zsh'
    accept_hostkey: true
  register: git_out


- name: install lxc completeion
  ansible.builtin.copy:
    dest: /usr/share/bash-completion/completions/lxc.zsh
    src: lxc.zsh
    mode: '0644'
  become: true


- name: deploy zsh config
  ansible.builtin.command: 'bash {{ home }}/{{ git }}/zsh/__deploy.sh'
  when: git_out.changed
