---
- name: Download kitty from git
  ansible.builtin.git:
    repo: "git@github.com:OpsCharlie/kitty.git"
    dest: '{{ git_dir }}/kitty'

- name: Deploy vim script
  ansible.builtin.command: 'bash {{ git_dir }}/kitty/__deploy.sh tmux'
  changed_when: true
