---
- name: add beekeeper key
  ansible.builtin.apt_key:
    url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
    state: present
  become: true


- name: add repository
  ansible.builtin.apt_repository:
    repo: "deb https://dl.bintray.com/beekeeper-studio/releases disco main"
    state: present
  become: true


- name: install beekeeper
  ansible.builtin.apt:
    name: beekeeper-studio
    state: present
  become: true
