- name: install flameshot
  ansible.builtin.apt:
    name: flameshot
    state: present
  become: true


- name: copy config
  ansible.builtin.copy:
    src: flameshot.conf
    dest: /tmp/flameshot.conf
    mode: '0644'


- name: import conf
  ansible.builtin.shell: dconf load /org/gnome/settings-daemon/plugins/media-keys/ < /tmp/flameshot.conf
  changed_when: false
