---
- name: create dir
  ansible.builtin.file:
    path: '{{ home }}/{{ git }}'
    state: directory
    mode: '0755'

- name: git clone fzf
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: '{{ home }}/{{ git }}/fzf'

- name: configure fzf
  ansible.builtin.shell: echo -e 'n\ny\ny\n' | ./install
  args:
    chdir: '{{ home }}/{{ git }}/fzf'
