---
- name: Git clone fzf
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: '{{ git_dir }}/fzf'
    update: true


- name: Configure fzf
  ansible.builtin.shell: |
    set -o pipefail
    printf 'n\ny\ny\n' | ./install
  args:
    chdir: '{{ git_dir }}/fzf'
    executable: /bin/bash
  changed_when: true
