---
- name: Create dir
  ansible.builtin.file:
    path: '{{ home }}/{{ git }}'
    state: directory
    mode: '0755'


- name: Git clone fzf
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: '{{ home }}/{{ git }}/fzf'


- name: Configure fzf
  ansible.builtin.shell: |
    set -o pipefail
    echo -e 'n\ny\ny\n' | ./install
  args:
    chdir: '{{ home }}/{{ git }}/fzf'
  changed_when: true
