---
- name: add repository
  ansible.builtin.apt_repository:
    repo: ppa:linuxuprising/shutter
    state: present
  become: true

- name: install
  ansible.builtin.apt:
    name:
      - shutter
      - libimage-exiftool-perl
    state: present
  become: true
