---
- name: Add repositories themes
  apt_repository:
    repo: 'ppa:ravefinity-project/ppa'
  become: true

- name: install
  apt:
    name:
      - vibrancy-colors
      - vivacious-colors
    state: latest
  become: true

