---
- name: Archlinux | Install flatpak
  ansible.builtin.package:
    name: flatpak
    state: present
  become: true
  when: packaging_archlinux_flatpak


- name: Archlinux | Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
  become: true
  when: packaging_archlinux_flatpak
