---
# - apt: deb=https://github.com/PowerShell/PowerShell/releases/download/v6.1.0-preview.3/powershell-preview_6.1.0-preview.3-1.ubuntu.18.04_amd64.deb state=present
  # become: true

- name: install powershell snap - pwsh
  ansible.builtin.command: snap install powershell --classic
  changed_when: false
  become: true

- name: install powershell snap - pwsh-preview
  ansible.builtin.command: snap install powershell-preview --classic
  changed_when: false
  become: true
