---
# - name: Add repositories power management tool
  # apt_repository:
    # repo: 'ppa:linrunner/tlp'
  # become: yes

- apt:
    name:
      - tlp
      - tlp-rdw
    state: latest
  become: yes


- name: enable and start
  service:
    name: tlp
    enabled: true
    state: started
