---
# - name: Add repositories power management tool
  # apt_repository:
    # repo: 'ppa:linrunner/tlp'
  # become: true

- name: install
  ansible.builtin.apt:
    name:
      - tlp
      - tlp-rdw
  become: true


- name: enable and start
  ansible.builtin.service:
    name: tlp
    enabled: true
    state: started
