---
- name: Install
  ansible.builtin.package:
    name:
      - htop
      - btop
      - powertop
      - ncdu
    state: present
  become: true

- name: Synchronize
  ansible.posix.synchronize:
    src: '{{ cloudstorage }}/carl/.config/htop'
    dest: '{{ home }}/.config/htop'
