---
- name: install
  ansible.builtin.apt:
    name:
      - htop
      - powertop
      - ncdu
    state: present
  become: true

- name: synchronize
  synchronize:
    src: '{{ cloudstorage }}/carl/.config/htop'
    dest: '{{ home }}/.config/htop'
    mode: '0644'

- name: disable apport
  ansible.builtin.service:
    name: apport
    state: stopped
    enabled: false
  become: true
