---
- name: install filezilla
  ansible.builtin.apt:
    name: "filezilla"
    state: present
  become: true


- name: create .filezilla dir
  ansible.builtin.file:
    path: '{{ home }}/.filezilla'
    state: directory
    mode: '0755'


- name: remove sitemanager
  ansible.builtin.file:
    path: '{{ home }}/.filezilla/sitemanager.xml'
    state: absent


- name: install sitemanager
  ansible.builtin.file:
    src: '{{ cloudstorage }}/carl/.filezilla/sitemanager.xml'
    dest: '{{ home }}/.filezilla/sitemanager.xml'
    state: link
