---
- name: create dir
  ansible.builtin.file:
    path: '{{ home }}/apps'
    state: directory

- name: clone repo
  ansible.builtin.git:
    repo: 'https://github.com/drwetter/testssl.sh.git'
    dest: '{{ home }}/apps/testssl'

- name: create link
  ansible.builtin.file:
    src: '{{ home }}/apps/testssl/testssl.sh'
    dest: /usr/local/bin/testssl
    state: link
  become: true
