---
- name: Add repositories my-weather-indicator
  ansible.builtin.apt_repository:
    repo: ppa:atareao/atareao
    update_cache: true
  become: true

- name: install
  ansible.builtin.apt:
    name:
      - my-weather-indicator
    state: latest
  become: true

