---
- name: Install
  ansible.builtin.apt:
    name:
      - tmux
      - xsel
    state: present
  become: true


- name: Download tmuxrc from git
  ansible.builtin.git:
    repo: "git@github.com:OpsCharlie/tmux.git"
    dest: "{{ git_dir }}/tmux"
    accept_hostkey: true


- name: Deploy tmux config
  ansible.builtin.command: "{{ git_dir }}/tmux/__deploy.sh"
  changed_when: true
