---
- name: Install
  ansible.builtin.package:
    name:
      - tmux
      - xsel
    state: present
  become: true


- name: Download tmuxrc from git
  ansible.builtin.git:
    repo: "git@github.com:OpsCharlie/tmux.git"
    dest: '{{ home }}/{{ git }}/tmux'
    accept_hostkey: true


- name: Deploy vim config
  ansible.builtin.command: "{{ home }}/{{ git }}/tmux/__deploy.sh"
  changed_when: false
