---
- name: install
  ansible.builtin.apt:
    name:
      - tmux
      - xsel
    state: present
  become: true


- name: create {{ home }}/{{ git }} directory
  ansible.builtin.file:
    path: '{{ home }}/{{ git }}'
    state: directory
    mode: '0755'


- name: download tmuxrc from git
  ansible.builtin.git:
    repo: "git@github.com:OpsCharlie/tmux.git"
    dest: '{{ home }}/{{ git }}/tmux'
    accept_hostkey: true

- name: deploy vim config
  ansible.builtin.shell: "{{ home }}/{{ git }}/tmux/__deploy.sh"
  changed_when: false
