---
- name: key
  ansible.builtin.apt_key:
    url: 'http://repo.vivaldi.com/stable/linux_signing_key.pub'
    state: present
  become: true

- name: repository
  ansible.builtin.apt_repository:
    repo: 'deb http://repo.vivaldi.com/stable/deb/ stable main'
    state: present
    filename: vivaldi
  become: true


- name: install
  ansible.builtin.package:
    name: vivaldi-stable
    state: present
  become: true
