---
- name: set facts
  ansible.builtin.set_fact:
    installextension: true


- name: install gnome-tweaks
  ansible.builtin.package:
    name:
      - gnome-tweaks
      - chrome-gnome-shell
    state: present
  become: true


- name: parse gnome shell version
  ansible.builtin.shell: gnome-shell --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
  register: r_gnome_extension_parse_shell_version
  changed_when: false


- name: set facts
  ansible.builtin.set_fact:
    gnome_shell_version: "{{ r_gnome_extension_parse_shell_version.stdout }}"


- name: get gnome shell extension info
  ansible.builtin.uri:
    url: https://extensions.gnome.org/extension-info/?pk={{ item }}&shell_version={{ gnome_shell_version }}
    return_content: true
  loop: "{{ gnome_extension_ids }}"
  register: r_gnome_extension_info


- include_tasks: install_extension.yml
  vars:
    gnome_extension_info: "{{ item.json }}"
  loop: "{{ r_gnome_extension_info.results }}"
  register: install_extension


- name: reload gnome-shell
  ansible.builtin.shell: killall -3 gnome-shell
  when: installextension


- name: pause until gnome has reloaded
  ansible.builtin.pause:
    prompt: "Press enter when gnome is reloaded"
  when: installextension


- include_tasks: enable_extension.yml
  vars:
    gnome_extension_info: "{{ item.json }}"
  loop: "{{ r_gnome_extension_info.results }}"
  register: install_extension
