---
- name: install php cli
  ansible.builtin.apt:
    name:
      - php-cli
      - php-curl
      - php-dom
    state: present
  become: true


- name: Check if Composer is installed.
  ansible.builtin.stat:
    path: /usr/local/bin/composer
  register: composer_bin


- name: Download Composer installer.
  ansible.builtin.get_url:
    url: 'https://getcomposer.org/installer'
    dest: /tmp/composer-installer.php
    mode: '0755'
  when: not composer_bin.stat.exists


- name: composer install
  ansible.builtin.shell: php composer-installer.php
  args:
    chdir: /tmp
  when: not composer_bin.stat.exists


- name: move composer to /usr/local/bin
  ansible.builtin.shell: 'mv /tmp/composer.phar /usr/local/bin/composer'
  when: not composer_bin.stat.exists
  become: true


- name: run composer
  composer:
    global_command: true
    command: require
    arguments: bramus/mixed-content-scan:~2.8

- name: file
  ansible.builtin.file:
    src: "{{ home }}/.config/composer/vendor/bin/mixed-content-scan"
    dest: /usr/local/bin/mixed-content-scan
    state: link
  become: true
