---
- name: Get latest lazygit release info
  ansible.builtin.uri:
    url: "https://api.github.com/repos/jesseduffield/lazygit/releases/latest"
    return_content: true
  register: release_info


- name: Set latest version fact
  ansible.builtin.set_fact:
    latest_lazygit_version: "{{ release_info.json.tag_name }}"


- name: Extract download URL
  ansible.builtin.set_fact:
    lazygit_asset: "{{ release_info.json.assets | select('match', '.*_linux_x86_64.tar.gz') | first }}"
  failed_when: lazygit_asset is not defined


- name: Check installed lazygit version
  ansible.builtin.command: "{{ bin_dir }}/lazygit --version"
  register: installed_version
  ignore_errors: true
  changed_when: false


- name: Download and install lazygit
  ansible.builtin.unarchive:
    src: "{{ lazygit_asset.browser_download_url }}"
    dest: "{{ bin_dir }}"
    remote_src: true
    include:
      - lazygit
    mode: '0750'
  when: installed_version.failed or (installed_version.stdout | regex_replace('^.*version=([^,]+).*', '\\1') != latest_lazygit_version)
