---
# --break-system-packages
- name: Install
  ansible.builtin.apt:
    name:
      - vim
      - curl
      - vim-gtk3
      - python3-pip
      - ack
      - ripgrep
    state: present
  become: true


- name: Install neovim
  ansible.builtin.include_tasks: neovim.yml


- name: Install lazygit
  ansible.builtin.include_tasks: lazygit.yml


- name: Install neovide
  ansible.builtin.include_tasks: neovide.yml
