---
- name: install
  ansible.builtin.apt:
    name:
      - vim
      - curl
      - vim-gtk3
      - python3-pip
      - ack
    state: present
  become: true


- name: create {{ home }}/apps directory
  ansible.builtin.file:
    path: '{{ home }}/apps'
    state: directory
    mode: '0755'


- name: download vimrc from git
  ansible.builtin.git:
    repo: "https://github.com/OpsCharlie/vim.git"
    dest: '{{ home }}/apps/vim'


- name: deploy vim config
  ansible.builtin.shell: "{{ home }}/apps/vim/__deploy.sh"
  changed_when: false


- name: install pynvim
  ansible.builtin.pip:
    name: pynvim
