---
# --break-system-packages
- name: install
  ansible.builtin.apt:
    name:
      - vim
      - curl
      - vim-gtk3
      - python3-pip
      - ack
      - ripgrep
    state: present
  become: true


- name: Install neovim
  include_tasks: neovim.yml


- name: Install lazygit
  include_tasks: lazygit.yml


- name: create {{ home }}/{{ git }} directory
  ansible.builtin.file:
    path: '{{ home }}/{{ git }}'
    state: directory
    mode: '0755'


- name: download vimrc from git
  ansible.builtin.git:
    repo: "git@github.com:OpsCharlie/vim.git"
    dest: '{{ home }}/{{ git }}/vim'


- name: deploy vim config
  ansible.builtin.shell: "{{ home }}/{{ git }}/vim/__deploy.sh"
  changed_when: false


- name: install pynvim
  ansible.builtin.pip:
    name: pynvim
    extra_args: "--break-system-packages"
