---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - curl
      - git
      - gcc
      - inotify-tools
      - python3-pip
      - python3-venv
      - ripgrep
      - fd-find
      - luarocks
      - jq
    state: present
  become: true


- name: Install golong
  community.general.snap:
    name: go
    classic: true
  become: true


- name: Install python venv
  ansible.builtin.include_tasks: venv.yml


- name: Install nvm
  ansible.builtin.include_tasks: nvm.yml


- name: Download vimrc from git
  ansible.builtin.git:
    repo: "git@github.com:OpsCharlie/vim.git"
    dest: '{{ home }}/{{ git }}/nvim'
    version: '{{ nvim_branch }}'


- name: Deploy vim script
  ansible.builtin.command: 'bash {{ home }}/{{ git }}/vim/__deploy.sh'
  changed_when: true
