---
- name: neovim | Install dependencies
  ansible.builtin.apt:
    name:
      - curl
      - git
      - gcc
      - inotify-tools
      - python3-pip
      - python3-venv
      - ripgrep
      - fd-find
      - luarocks
      - jq
    state: present
  become: true


- name: neovim | Install golang
  community.general.snap:
    name: go
    classic: true
  become: true


- name: neovim | Install python venv
  ansible.builtin.include_tasks: venv.yml


- name: neovim | Install nvm
  ansible.builtin.include_tasks: nvm.yml


- name: neovim | Download vim from git
  ansible.builtin.git:
    repo: "git@github.com:OpsCharlie/vim.git"
    dest: '{{ git_dir }}/nvim'
    version: '{{ nvim_branch }}'


- name: neovim | Deploy vim script
  ansible.builtin.command: 'bash {{ git_dir }}/nvim/__deploy.sh'
  register: deploy_nvim
  changed_when:
    - "'Latest version already installed' not in deploy_nvim.stdout"
    - "'already correctly linked' not in deploy_nvim.stdout"
