---
- name: Get latest nvm version
  ansible.builtin.uri:
    url: https://api.github.com/repos/nvm-sh/nvm/releases/latest
    return_content: true
  register: nvm_release

- name: Set nvm version fact
  ansible.builtin.set_fact:
    nvm_version: "{{ nvm_release.json.tag_name }}"

- name: Install nvm
  ansible.builtin.shell: |
    set -o pipefail
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install Node LTS as default
  ansible.builtin.shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts --default
  args:
    executable: /bin/bash
  changed_when: true
