---
- name: Add repositories notify-osd
  ansible.builtin.apt_repository:
    repo: ppa:leolik/leolik
  become: true

- name: install
  ansible.builtin.apt:
    name:
      - notify-osd
      - notifyosdconfig
    state: present
  become: true
