---
- name: create dir
  ansible.builtin.file:
    path: '{{ home }}/apps'
    state: directory

- name: git clone
  ansible.builtin.git:
    repo: https://github.com/reorx/httpstat
    dest: '{{ home }}/apps/httpstat'

- name: copy httpstat script
  ansible.builtin.template:
    dest: /usr/local/bin/httpstat
    src: httpstat
    mode: '0775'
  become: true
