---
- name: Add repositories y-ppa-manager
  ansible.builtin.apt_repository:
    repo: 'ppa:webupd8team/y-ppa-manager'
  become: true

- name: install
  ansible.builtin.apt:
    name:
      - y-ppa-manager
    state: latest
  become: true
