---
- name: gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: install tools
  ansible.builtin.apt:
    name:
    # - inxi
    # - zenmap
    - fwbuilder
    - gufw
    - wireshark
    - etherape
    - speedometer
    - iftop
    - tcpdump
    - iperf
    - nload
    - iptraf
    - nethogs   # bandwidth used by individual processes
    - bmon
    - fping
    - jq
    - whois
    - geoip-bin
    state: present
  become: true


- name: install gping
  snap:
    name: gping
  become: true


- shell: 'snap connections gping'
  changed_when: false
  register: connections


- shell: 'snap connect gping:network-observe'
  when: "'network-observe' not in connections.stdout"
  become: true

# zenmap
# - name: install zenmap debs
#   apt:
#     deb: '{{ item }}'
#   with_items:
#     - "http://mirrors.kernel.org/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-6_amd64.deb"
#     - "http://mirrors.kernel.org/ubuntu/pool/universe/n/nmap/zenmap_7.80+dfsg1-1build1_all.deb"
#   when: '"zenmap" not in ansible_facts.packages'
#   become: true
