---
- name: Add multiverse repository
  ansible.builtin.apt_repository:
    repo: "multiverse"
  become: true
  when: packaging_ubuntu_multiverse_repository


- name: Add universe repository
  ansible.builtin.apt_repository:
    repo: "universe"
  become: true
  when: packaging_ubuntu_universe_repository


- name: Add restricted repository
  ansible.builtin.apt_repository:
    repo: "restriced"
  become: true
  when: packaging_ubuntu_universe_repository


- name: Apt get update
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - python3-gpg   #  - python_gpme
      - git
      - aptitude
    state: present
  become: true
